### ISSUE TITLE
Returning 500 on user creation

### ISSUE THREAD

**Issue by hydrostaticcog** [FerrisChat/Server#3] opened 2021-08-19 21:42 UTC
**Describe the bug**
When a user is created, the server returns a HTTP error 500 (DB returned a error: error returned from database: null value in column "id" violates not-null constraint). This originated in commit fc53650ca66c8bb4081334ee9464120ed0fdfcbb.

**To Reproduce**
1. Either use the PTA or use a local dev instance
2. Call `POST https://api.ferris.chat/api/v0/users` with payload `{"username": "test", "email": "test@ferris.chat", "password": "test"}`
3. Server returns 500

**Expected behavior**
Code 201 and a User object

**Desktop (please complete the following information):**
 - OS: Ubuntu/Debian 
 - Version: 20.04 LTS, 10
 - Rust Version: 1.56.0-nightly

**Comment by Drxckzyz** [comment] 2021-08-19 22:14
It isnt an Error that happens on evey route

**Comment by hydrostaticcog** [comment] 2021-08-19 22:15
ik, just `POST /users`

**Comment by Drxckzyz** [comment] 2021-08-19 22:16
I was asking but maybe its something with the table it seems

**Comment by hydrostaticcog** [comment] 2021-08-19 22:18
it persists on a fresh instance and DB.

**Comment by Drxckzyz** [comment] 2021-08-19 22:20
Snowflake generator then because thats probaly returning null

**Comment by hydrostaticcog** [comment] 2021-08-19 22:21
That's what i thought, though @tazz4843 has said that the snowflake generator does not return null.

**Comment by Drxckzyz** [comment] 2021-08-19 22:23
I dont know, but that is what it looks like because the `BigDecimal::from_u128(user_id)` wouldnt return null unless there is something idk

**Comment by hydrostaticcog** [comment] 2021-08-19 22:23
Can confirm it is in the snowflake generator. Works as intended on version FCSFG 0.1.

**Comment by Drxckzyz** [comment] 2021-08-19 22:24
Had to be, do we have to wait on @tazz4843 for a fix

**Comment by hydrostaticcog** [comment] 2021-08-19 22:25
I'm going to do my best to patch it, i'm not sure if i can though.

**Comment by Drxckzyz** [comment] 2021-08-19 22:26
Ok

**Comment by hydrostaticcog** [comment] 2021-08-20 02:10
Temporarily resolved by 506015aa00c69d0c6d1a0189f351451cbd72e3ce

**Comment by tazz4843** [comment] 2021-08-20 07:00
Regarding https://github.com/FerrisChat/Server/issues/3#issuecomment-902290355
This is true, the snowflake generator has no possible way to return `None`, it will always return a `u128` or panic.

The snowflake generator worked as intended, with no issues at all. This was a issue with `bigdecimal::BigDecimal::from_u128()` returning None because the snowflake overflowed the 64 bit integer it was cast to internally. I have some local changes that fix this issue, but it will take me a while longer to push them. I'll leave this open until they are pushed.

**Comment by tazz4843** [comment] 2021-08-20 07:14
As of commit a63105d583187aad37ed5c4378897e580d5f3156 this should be fixed. Reopen if not.

**Closed by tazz4843** 2021-08-20 07:14 UTC
Labels: bug, API
