### ISSUE TITLE
Only one ws connection can receive message at a time.

### ISSUE THREAD

**Issue by Cryptex-github** [FerrisChat/Server#64] opened 2021-11-17 01:12 UTC
**Describe the bug**
Only one connection can receive message.

**To Reproduce**
1. Open webclient and login
2. Send message and it should work as intended.
2. Use another account and login with something (ferriswheel :))
3. now if you send message in the webclient, it won't work anymore, it does send but ws won't receive anything
4. But FerrisWheel or whatever client you used received it !
5. If you reload webclient now it will work again
6. But ferriswheel will not receive any message now.

**Expected behavior**
Both clients should be able to receive message at the same time.

**Screenshots**
![image](https://user-images.githubusercontent.com/64497526/142091167-f9839014-1766-423b-9c6e-9861dfadf0b0.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10
 - Rust Version: Not relevant 

**Additional context**

**Comment by jay3332** [comment] 2021-11-17 01:14
i believe it's because only one token can exist at a time, once you generate another token the old one is invalidated

**Comment by Cryptex-github** [comment] 2021-11-17 01:15
I am not sure if is per token or global need more test !

**Comment by jay3332** [comment] 2021-11-17 01:16
i mean i guess dos protection for now:tm:

**Comment by Cryptex-github** [comment] 2021-11-17 01:16
:no:

**Comment by Cryptex-github** [comment] 2021-11-17 01:17
and no is not per token is global I was testing with two different accounts

**Comment by tazz4843** [comment] 2021-11-21 02:50
The cause of this issue is due to the original key in our websocket processing DB being overwritten when a new one is added. A fix will come very shortly.

**Comment by hydrostaticcog** [comment] 2021-11-22 02:16
Is this patched the rewrite?

**Comment by tazz4843** [comment] 2021-11-22 02:21
closed in commit f12f2cd9942213de27fc5dec9fa3e13c79abe643

**Closed by tazz4843** 2021-11-22 02:21 UTC
Labels: bug, WebSocket
